#!/bin/bash
set -e

# -----------------------------
# Install Docker
# -----------------------------
yum update -y
amazon-linux-extras install docker -y
systemctl enable --now docker
usermod -a -G docker ec2-user

# -----------------------------
# Install AWS CLI v2
# -----------------------------
curl -fsSL https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /tmp/awscliv2.zip
yum install -y unzip
unzip -q /tmp/awscliv2.zip -d /tmp
/tmp/aws/install



# -----------------------------
# Docker network
# -----------------------------
docker network create practicas_net || true

# -----------------------------
# Run service helper
# -----------------------------
run_service() {
  NAME="$1"
  PORT="$2"
  IMAGE_REPO="$3"

  IMAGE="dapaeza/$IMAGE_REPO:latest"

  echo "Starting $NAME on port $PORT"

  docker pull "$IMAGE"

  if docker ps -a --format '{{.Names}}' | grep -q "^$NAME$"; then
    docker rm -f "$NAME"
  fi

  docker run -d \
    --name "$NAME" \
    --network practicas_net \
    --restart unless-stopped \
    -p "$PORT:$PORT" \
    -e PORT="$PORT" \
    -e NODE_ENV=production \
    -e DATABASE_URL="postgresql://$db_user:$db_password@$db_host:$db_port/$db_name" \
    -e REDIS_URL="redis://$redis_host:$redis_port" \
    -e AUTH_SERVICE_URL="http://auth-service:3001" \
    -e USER_SERVICE_URL="http://user-management:3002" \
    -e REGISTRATION_SERVICE_URL="http://registration-service:3003" \
    -e TRACKING_SERVICE_URL="http://tracking-service:3008" \
    -e COMMUNICATION_SERVICE_URL="http://communication-service:3004" \
    -e NOTIFICATION_SERVICE_URL="http://notification-service:3005" \
    -e DOCUMENT_SERVICE_URL="http://document-management-service:3006" \
    -e REPORTING_SERVICE_URL="http://reporting-service:3007" \
    "$IMAGE"
}


# -----------------------------
# Start services (generated by Terraform)
# -----------------------------
${run_services_block}
